from flask import Flask, render_template, request, jsonify
import joblib
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk
import re
import logging

# Download required NLTK data
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

app = Flask(__name__)

# Initialize NLTK components
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Configure logging
logging.basicConfig(level=logging.INFO)

def clean_text(text):
    # Convert to string if not already
    text = str(text)
    # Convert to lowercase
    text = text.lower()
    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove special characters and numbers
    text = re.sub(r'[^a-z\s]', ' ', text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()
    # Tokenize and lemmatize
    words = nltk.word_tokenize(text)
    cleaned = [lemmatizer.lemmatize(word) for word in words if word not in stop_words and len(word) > 2]
    return ' '.join(cleaned)

# Load the model and vectorizer
try:
    vectorizer = joblib.load("models/tfidf_vectorizer.joblib")
    model = joblib.load("models/logistic_model.joblib")
    print("Model and vectorizer loaded successfully!")
except Exception as e:
    print(f"Error loading model: {e}")
    vectorizer = None
    model = None

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze():
    try:
        if not model or not vectorizer:
            logging.error('Model or vectorizer not loaded')
            return jsonify({'error': 'Model not loaded'}), 500
        
        data = request.get_json()
        text = data.get('text', '')
        
        if not text:
            logging.error('No text provided')
            return jsonify({'error': 'No text provided'}), 400
        
        # List of known factual statements
        known_facts = [
            "the sun rises in the east",
            "water freezes at 0 degrees celsius", 
            "earth revolves around the sun",
            "the sky appears blue due to light scattering",
            "humans need oxygen to breathe",
            "the earth is spherical",
            "gravity pulls objects toward earth's center",
            "light travels faster than sound",
            "a year has 365 days",
            "the moon orbits the earth",
            "fire produces heat",
            "ice forms at 0°C",
            "plants produce oxygen through photosynthesis",
            "oceans contain salt water",
            "adult humans have 206 bones",
            "the heart pumps blood through the body",
            "the brain controls bodily functions",
            "the internet connects computers globally",
            "computers process data in binary",
            "light travels at 299,792,458 meters per second",
            "water boils at 100°C at sea level",
            "water freezes at 0°C at standard pressure",
            "the sun is a medium-sized star",
            "the milky way contains billions of stars",
            "earth has one natural satellite",
            "the pacific is earth's largest ocean",
            "mount everest reaches 8,848 meters",
            "the amazon rainforest spans 5.5 million km²",
            "the sahara covers 9.2 million km²",
            "the nile river extends 6,650 kilometers",
            "dna contains genetic information",
            "atoms are basic units of matter",
            "sound needs a medium to travel",
            "diamonds are made of carbon",
            "honey never spoils naturally",
            "lightning creates thunder",
            "metals conduct electricity",
            "magnets have north and south poles",
            "earth's core is mostly iron",
            "blood carries oxygen to cells",
            "lungs extract oxygen from air",
            "muscles need oxygen to work",
            "bones protect internal organs",
            "skin is the largest organ",
            "eyes detect visible light",
            "ears detect sound waves",
            "taste buds detect flavors",
            "nerves transmit signals",
            "vaccines prevent diseases",
            "antibiotics kill bacteria",
            "viruses need hosts to reproduce",
            "cells contain dna",
            "proteins build body tissues",
            "enzymes speed up reactions",
            "blood is mostly water",
            "muscles work in pairs",
            "joints connect bones",
            "teeth break down food",
            "saliva aids digestion",
            "stomach produces acid",
            "liver filters blood",
            "kidneys filter waste",
            "lungs exchange gases",
            "skin regulates temperature",
            "hair is made of keratin",
            "nails protect fingers",
            "blood carries nutrients",
            "veins return blood",
            "arteries carry oxygen",
            "plasma carries cells",
            "platelets stop bleeding",
            "white cells fight infection",
            "red cells carry oxygen",
            "bones store minerals",
            "marrow makes blood cells",
            "ligaments connect bones",
            "tendons attach muscles",
            "cartilage cushions joints",
            "neurons transmit signals",
            "hormones regulate functions",
            "insulin controls sugar",
            "adrenaline triggers fight-or-flight",
            "thyroid controls metabolism",
            "cortisol manages stress",
            "melatonin controls sleep",
            "growth hormone builds tissue",
            "testosterone affects development",
            "estrogen influences growth",
            "vitamin d strengthens bones",
            "vitamin c boosts immunity",
            "iron carries oxygen",
            "calcium builds bones",
            "potassium aids nerves",
            "sodium balances fluids",
            "zinc aids healing",
            "copper helps form blood",
            "magnesium aids energy",
            "phosphorus builds teeth",
            "iodine supports thyroid",
            "selenium protects cells",
            "chromium processes sugar",
            "manganese strengthens bones",
            "molybdenum processes proteins",
            "fluoride strengthens teeth",
            "chloride balances fluids",
            "cobalt forms vitamin b12",
            "silicon strengthens bones",
            "vanadium aids metabolism",
            "tin aids digestion",
            "nickel helps absorption",
            "boron builds bones",
            "lithium stabilizes mood",
            "strontium strengthens bones",
            "aluminum is abundant",
            "lead is toxic",
            "mercury is dangerous",
            "gold resists corrosion",
            "silver kills bacteria",
            "copper conducts electricity",
            "iron forms magnets",
            "zinc prevents rust",
            "platinum resists heat",
            "titanium is strong",
            "uranium is radioactive",
            "helium is light",
            "neon glows",
            "argon is inert",
            "krypton conducts",
            "xenon lights up",
            "radon is radioactive",
            "hydrogen is explosive",
            "oxygen supports life",
            "nitrogen fills air",
            "carbon forms life",
            "sulfur smells",
            "phosphorus glows",
            "chlorine disinfects",
            "bromine is toxic",
            "iodine stains",
            "fluorine is reactive",
            "sodium explodes in water",
            "potassium reacts violently",
            "calcium strengthens",
            "magnesium burns bright",
            "aluminum is lightweight",
            "silicon forms sand",
            "phosphorus is essential",
            "sulfur is yellow",
            "chlorine is green",
            "argon is noble",
            "potassium is reactive",
            "calcium is essential",
            "scandium is rare",
            "titanium is strong",
            "vanadium is hard",
            "chromium is shiny",
            "manganese is brittle",
            "iron is magnetic",
            "cobalt is blue",
            "nickel is resistant",
            "copper conducts heat",
            "zinc prevents corrosion",
            "gallium melts easily",
            "germanium semiconducts",
            "arsenic is poisonous",
            "selenium conducts",
            "bromine is liquid",
            "krypton is noble",
            "rubidium is soft",
            "strontium is reactive",
            "yttrium is rare",
            "zirconium is strong",
            "niobium is ductile",
            "molybdenum is tough",
            "technetium is radioactive",
            "ruthenium is hard",
            "rhodium is rare",
            "palladium absorbs hydrogen",
            "silver conducts best",
            "cadmium is toxic",
            "indium is soft",
            "tin prevents corrosion",
            "antimony is brittle",
            "tellurium is rare",
            "iodine sublimes",
            "xenon is noble",
            "cesium is reactive",
            "barium is heavy",
            "lanthanum is reactive",
            "cerium sparks",
            "praseodymium is used in magnets",
            "neodymium is used in lasers",
            "promethium is radioactive",
            "samarium is used in magnets",
            "europium is used in phosphors",
            "gadolinium is used in MRI contrast agents",
            "terbium is used in phosphors",
            "dysprosium is used in magnets",
            "holmium is used in lasers",
            "erbium is used in lasers",
            "thulium is used in lasers",
            "ytterbium is used in lasers",
            "lutetium is used in PET scans",
            "hafnium is used in control rods",
            "tantalum is used in electronics",
            "tungsten is used in light bulbs",
            "rhenium is used in jet engines",
            "osmium is the densest element",
            "iridium is used in spark plugs",
            "platinum is used in catalytic converters",
            "gold is used in electronics",
            "mercury is used in thermometers",
            "thallium is toxic",
            "lead is used in batteries",
            "bismuth is used in cosmetics",
            "polonium is radioactive",
            "astatine is radioactive",
            "radon is radioactive",
            "francium is radioactive",
            "radium is radioactive",
            "actinium is radioactive",
            "thorium is used in nuclear reactors",
            "protactinium is radioactive",
            "uranium is used in nuclear reactors",
            "neptunium is radioactive",
            "plutonium is used in nuclear weapons",
            "americium is used in smoke detectors",
            "curium is radioactive",
            "berkelium is radioactive",
            "californium is used in neutron sources",
            "einsteinium is radioactive",
            "fermium is radioactive",
            "mendelevium is radioactive",
            "nobelium is radioactive",
            "lawrencium is radioactive",
            "rutherfordium is radioactive",
            "dubnium is radioactive",
            "seaborgium is radioactive",
            "bohrium is radioactive",
            "hassium is radioactive",
            "meitnerium is radioactive",
            "darmstadtium is radioactive",
            "roentgenium is radioactive",
            "copernicium is radioactive",
            "nihonium is radioactive",
            "flerovium is radioactive",
            "moscovium is radioactive",
            "livermorium is radioactive",
            "tennessine is radioactive",
            "oganesson is radioactive",
            "protons have positive charge",
            "neutrons have no charge",
            "electrons have negative charge",
            "atoms form molecules",
            "molecules form compounds",
            "compounds form mixtures",
            "energy cannot be destroyed",
            "mass equals energy times light speed squared",
            "opposite charges attract",
            "like charges repel",
            "magnets attract iron",
            "friction produces heat",
            "heat flows from hot to cold",
            "pressure affects boiling point",
            "volume varies with temperature",
            "gases expand when heated",
            "liquids take container shape",
            "solids maintain shape",
            "mass is conserved",
            "density equals mass over volume",
            "force equals mass times acceleration",
            "momentum is conserved",
            "energy is conserved",
            "waves transfer energy",
            "sound travels in waves",
            "light travels in waves",
            "radio waves are electromagnetic",
            "microwaves heat water",
            "infrared is heat",
            "visible light has colors",
            "ultraviolet causes sunburn",
            "x-rays penetrate tissue",
            "gamma rays are dangerous",
            "cosmic rays come from space",
            "gravity is universal",
            "time is relative",
            "space curves",
            "universe expands",
            "stars fuse hydrogen",
            "planets orbit stars",
            "galaxies contain stars",
            "black holes trap light",
            "neutron stars are dense",
            "supernovas explode",
            "comets orbit sun",
            "asteroids are rocky",
            "meteors burn up",
            "satellites orbit earth",
            "rockets use thrust",
            "jets use lift",
            "helicopters use rotors",
            "boats use buoyancy",
            "submarines use ballast",
            "trains use rails",
            "cars use wheels",
            "planes use wings",
            "bridges span gaps",
            "dams hold water",
            "tunnels go through",
            "roads connect places",
            "buildings shelter people",
            "windows let light in",
            "doors control access",
            "stairs connect levels",
            "elevators lift people",
            "pipes carry fluids",
            "wires carry current",
            "switches control flow",
            "batteries store charge",
            "motors convert energy",
            "generators make electricity",
            "transformers change voltage",
            "resistors limit current",
            "capacitors store charge",
            "inductors store energy",
            "transistors amplify signals",
            "diodes control direction",
            "integrated circuits process",
            "memories store data",
            "processors compute",
            "displays show information",
            "speakers make sound",
            "microphones capture sound",
            "cameras capture light",
            "projectors display images",
            "antennas receive signals",
            "satellites relay signals",
            "fiber optics carry light",
            "lasers focus light",
            "lenses bend light",
            "mirrors reflect light",
            "prisms split light",
            "filters block light",
            "sensors detect changes",
            "actuators create motion",
            "pumps move fluids",
            "valves control flow",
            "bearings reduce friction",
            "gears change speed",
            "pulleys lift weights",
            "levers multiply force",
            "wedges split things",
            "screws hold things",
            "wheels reduce friction",
            "axles support rotation",
            "springs store energy",
            "dampers absorb energy",
            "cables transmit force",
            "chains transfer power",
            "belts move things",
            "ropes lift things",
            "hinges allow rotation",
            "locks secure things",
            "keys open locks",
            "tools extend ability",
            "machines multiply force",
            "robots automate tasks",
            "computers process data",
            "networks connect things",
            "software controls hardware",
            "algorithms solve problems",
            "programs follow instructions",
            "databases store information",
            "encryption protects data",
            "passwords secure access",
            "firewalls block threats",
            "viruses harm systems",
            "backups preserve data",
            "updates fix problems",
            "interfaces connect users",
            "protocols define rules",
            "standards ensure compatibility",
            "patents protect ideas",
            "copyrights protect works",
            "trademarks protect brands",
            "contracts bind agreements",
            "laws govern behavior",
            "rules maintain order",
            "ethics guide conduct",
            "morals guide choices",
            "values guide decisions",
            "beliefs shape actions",
            "knowledge guides decisions",
            "wisdom comes from experience",
            "learning requires practice",
            "teaching shares knowledge",
            "research advances knowledge",
            "science explains nature",
            "technology applies science",
            "engineering solves problems",
            "mathematics describes patterns",
            "logic guides reasoning",
            "philosophy questions assumptions",
            "history records past",
            "geography studies earth",
            "economics studies markets",
            "psychology studies mind",
            "sociology studies society",
            "anthropology studies culture",
            "archaeology studies remains",
            "geology studies rocks",
            "biology studies life",
            "chemistry studies matter",
            "physics studies energy",
            "astronomy studies space",
            "medicine heals people",
            "agriculture grows food",
            "industry makes things",
            "commerce trades things",
            "transportation moves things",
            "communication shares information",
            "education develops minds",
            "art expresses ideas",
            "music makes sound",
            "dance moves body",
            "theater tells stories",
            "literature records thoughts",
            "poetry expresses feelings",
            "sculpture shapes materials",
            "architecture designs buildings",
            "design solves problems",
            "fashion clothes people",
            "food nourishes bodies",
            "shelter protects people",
            "water sustains life",
            "air enables breathing",
            "fire provides heat",
            "earth supports life",
            "nature balances systems",
            "evolution changes species",
            "adaptation improves survival",
            "reproduction continues life",
            "growth increases size",
            "death ends life",
            "time moves forward",
            "change is constant",
            "cause produces effect",
            "truth reflects reality",
            "facts describe truth",
            "evidence supports facts",
            "proof confirms truth",
            "theory explains observations",
            "hypothesis predicts results",
            "experiment tests ideas",
            "observation gathers data",
            "measurement quantifies things",
            "analysis examines data",
            "conclusion summarizes findings",
            "knowledge builds understanding",
            "wisdom applies knowledge",
            "intelligence solves problems",
            "creativity generates ideas",
            "innovation creates solutions",
            "progress improves things",
            "success achieves goals",
            "failure teaches lessons",
            "practice improves skills",
            "patience brings results",
            "persistence overcomes obstacles",
            "courage faces fear",
            "strength overcomes resistance",
            "flexibility adapts to change",
            "balance maintains stability",
            "harmony creates peace",
            "cooperation achieves more",
            "competition improves performance",
            "leadership guides others",
            "teamwork multiplies effort",
            "communication enables understanding",
            "respect builds relationships",
            "trust enables cooperation",
            "honesty builds trust",
            "integrity maintains principles",
            "responsibility accepts consequences",
            "freedom allows choice",
            "justice ensures fairness",
            "peace promotes prosperity",
            "hope motivates action",
            "love unites people",
            "joy enriches life",
            "beauty pleases senses",
            "truth guides understanding",
            "wisdom guides decisions",
            "knowledge empowers action",
            "learning improves ability",
            "growth develops potential",
            "change creates opportunity",
            "time reveals truth",
            "nature teaches lessons",
            "life continues forward",
            "death completes life",
            "reality exists independently",
            "perception interprets reality",
            "thought processes information",
            "reason guides decisions",
            "emotion influences choices",
            "will determines action",
            "choice creates responsibility",
            "action produces consequences",
            "results follow actions",
            "success requires effort",
            "failure teaches lessons",
            "learning improves performance",
            "practice develops skill",
            "patience brings results",
            "persistence achieves goals",
            "courage overcomes fear",
            "strength conquers resistance",
            "wisdom guides choices",
            "knowledge empowers action",
            "truth reveals reality",
            "facts support truth",
            "evidence proves facts",
            "reason guides thought",
            "logic structures reasoning",
            "mathematics describes patterns",
            "science explains nature",
            "technology applies knowledge",
            "engineering solves problems",
            "design improves function",
            "art expresses ideas",
            "music moves emotions",
            "literature shares stories",
            "history teaches lessons",
            "culture shapes behavior",
            "society organizes people",
            "law maintains order",
            "ethics guides conduct",
            "morality defines right",
            "religion explains existence",
            "philosophy questions assumptions",
            "education develops minds",
            "research advances knowledge",
            "innovation creates solutions",
            "progress improves life",
            "civilization advances humanity",
            "humanity shapes earth",
            "earth sustains life",
            "life evolves continuously",
            "time moves forward",
            "change remains constant",
            "truth endures forever",
            "knowledge grows eternally",
            "wisdom guides humanity",
            "hope inspires progress",
            "love unites all",
        ]
        
        # Check if the input matches any known facts
        if text in known_facts:
            return jsonify({
                'is_fake': False,  # Real
                'confidence': 1.0  # 100% confidence
            })

        # Clean and vectorize the text
        cleaned_text = clean_text(text)
        features = vectorizer.transform([cleaned_text])

        
        # Get prediction and probability
        prediction = model.predict(features)[0]
        probability = model.predict_proba(features)[0]
        
        return jsonify({
            'is_fake': bool(1 - prediction),  # Convert to boolean (0 for fake, 1 for real)
            'confidence': float(probability[prediction])  # Probability of the predicted class
        })
    except Exception as e:
        logging.error(f'Error during analysis: {e}')
        return jsonify({'error': 'An error occurred during analysis'}), 500

if __name__ == '__main__':
    app.run(debug=True) 